##chap 4 python 物件

In [3]:
my_list0=[]
my_list1=list()
my_list2=['python','js','SQL']
print(my_list0)
print(my_list1)
print(my_list2)
print(my_list2[0])

[]
[]
['python', 'js', 'SQL']
python


In [4]:
my_list2=['python','js','SQL']
my_list2.append('java')
print(my_list2[3])
print(len(my_list2))
print(len(my_list2[0]))

java
4
6


In [7]:
my_list3=['python','js','SQL']
my_list3.insert(0,  'java')
print(my_list3)

['java', 'python', 'js', 'SQL']


In [8]:
my_list4=['java','python','js','SQL']
del my_list4[0]
print(my_list4)
del my_list4[-1]
print(my_list4)

['python', 'js', 'SQL']
['python', 'js']


In [9]:
my_list5=['java','python','js','SQL']
print('java'in my_list5)
print('go'in my_list5 )

True
False


In [10]:
a=[1,2]
print(a*5)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


In [11]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3]
print(b)
c=a[0:9:2]
print(c)
del a[7:9]
print(a)
print(min(a))
print(max(a))
print(a.index(1))
print(a.count(1))
a.reverse()
print(a)
a.sort()
print(a)

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7]
1
7
0
1
[7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7]


In [12]:
a_tuple=("python",'js','SQL')
b_list=['go','c#','vb']
b_tuple=tuple(b_list)
print(a_tuple)
print(b_tuple)

('python', 'js', 'SQL')
('go', 'c#', 'vb')


In [4]:
languages={}
languages={'name':'python','version':'3.7'}
print(languages['name'])
print(languages['version'])
print(languages)
print(languages.keys())
print(languages.values())
print(languages.items())
print('name'in languages)

python
3.7
{'name': 'python', 'version': '3.7'}
dict_keys(['name', 'version'])
dict_values(['python', '3.7'])
dict_items([('name', 'python'), ('version', '3.7')])
True


In [5]:
a={'name':'python','version':'3.7'}
b=a.copy()
print(b)
b.clear
print(a['name'])
print(a.get('name'))
a.update({'name':'java'})
print(a)

{'name': 'python', 'version': '3.7'}
python
python
{'name': 'java', 'version': '3.7'}


In [5]:
import numpy as np
my_array = np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [17]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print (c)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
